"use client";

import { useState } from "react";
import Link from "next/link";
import { PageFrame } from "@/components/PatioShell";

export default function ContactPage() {
  const [sent, setSent] = useState(false);
  return <PageFrame><section className="inner-hero contact-hero"><small>GET IN TOUCH</small><h1>Let&apos;s create something<br /><em>beautiful.</em></h1><p>Have a question, a custom furniture idea or a project in mind? We&apos;d love to hear from you.</p></section><section className="contact-introduction"><div><small>START A CONVERSATION</small><h2>Tell us about<br /><em>your space.</em></h2><p>From a single statement chair to a complete hospitality project, our team can help you find the right pieces, finishes and proportions.</p><div className="contact-note"><b>Our studio hours</b><span>Monday - Sunday | 9:00-17:00<br /></span></div></div><form onSubmit={(event) => { event.preventDefault(); setSent(true); }}>{sent ? <div className="form-success"><strong>Thank you.</strong><p>Your message is on its way. Our team will be in touch shortly.</p><button type="button" className="dark-button" onClick={() => setSent(false)}>Send another message</button></div> : <><div className="form-row"><label>First name<input required placeholder="Your first name" /></label><label>Last name<input required placeholder="Your last name" /></label></div><label>Email address<input required type="email" placeholder="you@example.com" /></label><label>What can we help with?<select defaultValue=""><option value="" disabled>Select an enquiry</option><option>Product enquiry</option><option>Custom furniture</option><option>Interior project</option><option>Trade partnership</option></select></label><label>Tell us a little more<textarea required placeholder="Tell us about your space, timeline and what you are looking for..." /></label><button className="dark-button" type="submit">Send message <span>â†’</span></button></>}</form></section><section className="contact-details"><div><span>01</span><h3>Call us</h3><p>+94 77 342 4994</p><small>Speak with our studio team</small></div><div><span>02</span><h3>Email us</h3><p>patiokinginfo@gmail.com</p><small>We reply within one business day</small></div><div><span>03</span><h3>Visit the studio</h3><p>Colombo, Sri Lanka</p><small>Appointments by arrangement</small></div></section><section className="contact-showroom"><div><small>COME SEE IT IN PERSON</small><h2>Good furniture<br /><em>feels different.</em></h2><p>Bring your ideas, your measurements or simply your curiosity. We&apos;ll make the coffee.</p></div></section></PageFrame>;
}
