"use client";

import { useState } from "react";
import { PageFrame } from "@/components/PatioShell";

export default function AppointmentPage() {
  const [submitted, setSubmitted] = useState(false);
  return <PageFrame><section className="appointment-page"><div className="appointment-hero"><small>PRIVATE CONSULTATION</small><h1>Let&apos;s make space<br /><em>for your ideas.</em></h1><p>Visit the Patio King studio for a one-to-one consultation. Bring your measurements, moodboards or simply a feeling you want to create.</p></div><div className="appointment-content"><div><small>BOOK A VISIT</small><h2>A considered conversation<br />starts here.</h2><p>Tell us a little about your project and preferred time. Our team will confirm your appointment by email or phone.</p><div className="appointment-details"><p><b>Studio hours</b><br />Monday – Friday · 9:00–17:00<br />Saturday · 10:00–14:00</p><p><b>Location</b><br />Colombo, Sri Lanka<br />Appointments by arrangement</p></div></div>{submitted ? <div className="appointment-success"><span>✓</span><h3>Request received.</h3><p>Thank you. We&apos;ll be in touch shortly to confirm your consultation.</p><button className="dark-button" onClick={() => setSubmitted(false)}>Book another visit</button></div> : <form className="appointment-form" onSubmit={(event) => { event.preventDefault(); setSubmitted(true); }}><div className="form-row"><label>First name<input required placeholder="Your first name" /></label><label>Last name<input required placeholder="Your last name" /></label></div><label>Email address<input required type="email" placeholder="you@example.com" /></label><label>Phone number<input required placeholder="+94 77 342 4994" /></label><label>What are you visiting for?<select defaultValue=""><option value="" disabled>Select a consultation type</option><option>Custom furniture</option><option>Home furnishing</option><option>Outdoor project</option><option>Trade consultation</option></select></label><div className="form-row"><label>Preferred date<input required type="date" /></label><label>Preferred time<select defaultValue=""><option value="" disabled>Select a time</option><option>09:00 – 11:00</option><option>11:00 – 13:00</option><option>14:00 – 16:00</option></select></label></div><label>Tell us about your project<textarea placeholder="Room type, approximate size, timeline or anything else that will help us prepare..." /></label><button className="dark-button" type="submit">Request appointment →</button></form>}</div></section></PageFrame>;
}
