"use client";

import { Suspense, useEffect, useMemo, useRef, useState } from "react";
import type { MutableRefObject } from "react";
import { Canvas, useThree } from "@react-three/fiber";
import { ContactShadows, Environment, Html, OrbitControls, RoundedBox, useGLTF } from "@react-three/drei";
import * as THREE from "three";
import type { OrbitControls as OrbitControlsImpl } from "three-stdlib";
import { getFurnitureModel } from "./furnitureModels";

type Furniture3DViewerProps = { furnitureType: string; width: number; length: number; height: number; material: string; finish: string; upholstery: string; color: string; onSaveImage?: (save: () => void) => void };
type ControlsApi = OrbitControlsImpl;
type Palette = { wood: string; upholstery: string; roughness: number; metalness: number };

const woodMaterials: Record<string, { color: string; roughness: number; metalness: number }> = { "Premium Wood": { color: "#9a6b43", roughness: .42, metalness: 0 }, "Natural Rattan": { color: "#c39a61", roughness: .76, metalness: 0 }, "Premium Upholstery": { color: "#737b78", roughness: .88, metalness: 0 }, Teak: { color: "#a85d3c", roughness: .48, metalness: 0 }, Walnut: { color: "#4a2d25", roughness: .38, metalness: 0 }, "Weather-resistant Aluminium": { color: "#798384", roughness: .28, metalness: .7 } };
const finishColors: Record<string, string> = { Natural: "#b18455", "Honey Oak": "#c58b4d", "Dark Walnut": "#3a2723", "Matte Black": "#151718", Whitewash: "#d5cec2" };
const fabricColors: Record<string, string> = { Linen: "#c9c0ae", "Cotton Blend": "#a9ada7", "Performance Velvet": "#526b64", "Outdoor Canvas": "#b5a78e", Leather: "#704838" };
const accentColors: Record<string, string> = { "Warm Neutral": "#bcae9d", "Forest Green": "#315348", Terracotta: "#a85f43", Charcoal: "#3c4142", "Natural Wood": "#a2783e" };

function useSceneCapture(onSaveImage?: (save: () => void) => void) {
  const { gl } = useThree();
  useEffect(() => { onSaveImage?.(() => { const link = document.createElement("a"); link.download = "patio-king-design.png"; link.href = gl.domElement.toDataURL("image/png"); link.click(); }); }, [gl, onSaveImage]);
  return null;
}

function usePalette(props: Furniture3DViewerProps): Palette {
  return useMemo(() => { const material = woodMaterials[props.material] ?? woodMaterials["Premium Wood"]; return { wood: props.material === "Premium Upholstery" ? material.color : finishColors[props.finish] ?? material.color, upholstery: accentColors[props.color] ?? fabricColors[props.upholstery] ?? "#c9c0ae", roughness: material.roughness, metalness: material.metalness }; }, [props.material, props.finish, props.color, props.upholstery]);
}

function Surface({ color, roughness, metalness = 0 }: { color: string; roughness: number; metalness?: number }) { const material = useMemo(() => new THREE.MeshStandardMaterial({ color, roughness, metalness }), [color, roughness, metalness]); return <primitive object={material} attach="material" />; }
function Leg({ x, z, color, height = .65 }: { x: number; z: number; color: string; height?: number }) { return <mesh position={[x, height / 2, z]} castShadow><cylinderGeometry args={[.055, .07, height, 20]} /><Surface color={color} roughness={.4} /></mesh>; }
function Cushion({ position, size, color }: { position: [number, number, number]; size: [number, number, number]; color: string }) { return <RoundedBox position={position} args={size} radius={.08} smoothness={4} castShadow><Surface color={color} roughness={.9} /></RoundedBox>; }

function ChairModel({ palette, stool = false, dining = false }: { palette: Palette; stool?: boolean; dining?: boolean }) {
  const seatWidth = stool ? .8 : 1.25; const seatDepth = stool ? .8 : 1.15; const seatHeight = stool ? .95 : .52; const backHeight = stool ? .35 : dining ? .72 : 1.02;
  return <group><Cushion position={[0, seatHeight, 0]} size={[seatWidth, .22, seatDepth]} color={palette.upholstery} />{!stool && <Cushion position={[0, seatHeight + backHeight / 2, -.45]} size={[seatWidth, backHeight, .16]} color={palette.upholstery} />}<Leg x={-.43 * seatWidth} z={-.4 * seatDepth} color={palette.wood} height={seatHeight} /><Leg x={.43 * seatWidth} z={-.4 * seatDepth} color={palette.wood} height={seatHeight} /><Leg x={-.43 * seatWidth} z={.4 * seatDepth} color={palette.wood} height={seatHeight} /><Leg x={.43 * seatWidth} z={.4 * seatDepth} color={palette.wood} height={seatHeight} />{!stool && <><mesh position={[-seatWidth / 2 + .06, seatHeight + .35, 0]} castShadow><boxGeometry args={[.1, .7, seatDepth]} /><Surface color={palette.wood} roughness={palette.roughness} /></mesh><mesh position={[seatWidth / 2 - .06, seatHeight + .35, 0]} castShadow><boxGeometry args={[.1, .7, seatDepth]} /><Surface color={palette.wood} roughness={palette.roughness} /></mesh></>}</group>;
}

function SofaModel({ palette }: { palette: Palette }) { return <group><Cushion position={[0, .55, 0]} size={[2.65, .28, 1.05]} color={palette.upholstery} /><Cushion position={[0, 1.12, -.42]} size={[2.65, 1, .2]} color={palette.upholstery} /><Cushion position={[-.72, .78, 0]} size={[.25, .68, 1.2]} color={palette.wood} /><Cushion position={[.72, .78, 0]} size={[.25, .68, 1.2]} color={palette.wood} /><Leg x={-.98} z={-.38} color={palette.wood} height={.28} /><Leg x={.98} z={-.38} color={palette.wood} height={.28} /><Leg x={-.98} z={.38} color={palette.wood} height={.28} /><Leg x={.98} z={.38} color={palette.wood} height={.28} /></group>; }
function TableModel({ palette, dining = false }: { palette: Palette; dining?: boolean }) { const width = dining ? 2.65 : 1.9; const depth = dining ? 1.3 : .95; return <group><RoundedBox position={[0, 1.02, 0]} args={[width, .15, depth]} radius={.05} smoothness={3} castShadow><Surface color={palette.wood} roughness={palette.roughness} /></RoundedBox>{[-1, 1].flatMap((x) => [-1, 1].map((z) => <Leg key={`${x}-${z}`} x={x * (width / 2 - .15)} z={z * (depth / 2 - .15)} color={palette.wood} height={1} />))}</group>; }
function BedModel({ palette }: { palette: Palette }) { return <group><RoundedBox position={[0, .42, 0]} args={[2.55, .3, 2.55]} radius={.06} smoothness={3} castShadow><Surface color={palette.wood} roughness={palette.roughness} /></RoundedBox><Cushion position={[0, .66, .05]} size={[2.35, .2, 2.25]} color={palette.upholstery} /><RoundedBox position={[0, 1.18, -1.16]} args={[2.62, 1.25, .18]} radius={.05} smoothness={3} castShadow><Surface color={palette.wood} roughness={palette.roughness} /></RoundedBox></group>; }
function CabinetModel({ palette }: { palette: Palette }) { return <group><RoundedBox position={[0, .85, 0]} args={[1.55, 1.55, .72]} radius={.04} smoothness={3} castShadow><Surface color={palette.wood} roughness={palette.roughness} /></RoundedBox><mesh position={[0, .86, .38]} castShadow><boxGeometry args={[1.28, 1.25, .025]} /><Surface color={palette.upholstery} roughness={.72} /></mesh><mesh position={[0, .86, .405]}><boxGeometry args={[.025, 1.18, .04]} /><Surface color={palette.wood} roughness={palette.roughness} /></mesh><Leg x={-.6} z={-.25} color={palette.wood} height={.22} /><Leg x={.6} z={-.25} color={palette.wood} height={.22} /><Leg x={-.6} z={.25} color={palette.wood} height={.22} /><Leg x={.6} z={.25} color={palette.wood} height={.22} /></group>; }
function OttomanModel({ palette }: { palette: Palette }) { return <group><RoundedBox position={[0, .5, 0]} args={[1.3, .7, 1.3]} radius={.18} smoothness={6} castShadow><Surface color={palette.upholstery} roughness={.9} /></RoundedBox><Leg x={-.42} z={-.42} color={palette.wood} height={.18} /><Leg x={.42} z={-.42} color={palette.wood} height={.18} /><Leg x={-.42} z={.42} color={palette.wood} height={.18} /><Leg x={.42} z={.42} color={palette.wood} height={.18} /></group>; }

function ProceduralFurniture({ props }: { props: Furniture3DViewerProps }) {
  const palette = usePalette(props); const type = props.furnitureType.toLowerCase(); const scale = [props.width / 100, props.height / 100, props.length / 100] as [number, number, number];
  const isSofa = type.includes("sofa"); const isTable = type.includes("table"); const isBed = type.includes("bed"); const isCabinet = /cupboard|console|cabinet/.test(type); const isStool = type.includes("stool"); const isOttoman = type.includes("ottoman"); const isDiningChair = type.includes("dining chair");
  return <group scale={scale} position={[0, 0, 0]}>{isBed ? <BedModel palette={palette} /> : isCabinet ? <CabinetModel palette={palette} /> : isTable ? <TableModel palette={palette} dining={type.includes("dining")} /> : isOttoman ? <OttomanModel palette={palette} /> : isSofa ? <SofaModel palette={palette} /> : <ChairModel palette={palette} stool={isStool} dining={isDiningChair} />}</group>;
}

function GltfFurniture({ url }: { url: string }) { const { scene } = useGLTF(url); return <primitive object={scene.clone()} />; }
function ViewerScene({ props, controlsRef, onSaveImage }: { props: Furniture3DViewerProps; controlsRef: MutableRefObject<ControlsApi | null>; onSaveImage?: (save: () => void) => void }) { const { camera } = useThree(); const model = getFurnitureModel(props.furnitureType); useSceneCapture(onSaveImage); useEffect(() => { camera.position.set(3.1, 2.15, 4.1); camera.lookAt(0, .7, 0); controlsRef.current?.reset(); }, [props.furnitureType, camera, controlsRef]); return <><color attach="background" args={["#eeeae4"]} /><ambientLight intensity={1.7} /><directionalLight castShadow position={[3, 5, 4]} intensity={2.4} shadow-mapSize={[2048, 2048]} /><directionalLight position={[-3, 2, -2]} intensity={.8} color="#fff4e5" /><Environment preset="studio" /><Suspense fallback={<Html center><span className="viewer-loading">Loading 3D preview...</span></Html>}>{model.kind === "gltf" && model.model ? <GltfFurniture url={model.model} /> : <ProceduralFurniture props={props} />}</Suspense><mesh rotation={[-Math.PI / 2, 0, 0]} position={[0, -.02, 0]} receiveShadow><circleGeometry args={[3.6, 64]} /><meshStandardMaterial color="#d5cec4" roughness={1} /></mesh><ContactShadows position={[0, 0, 0]} opacity={.32} scale={4.6} blur={2.5} far={3.4} /><OrbitControls ref={controlsRef} enablePan={false} minDistance={2.5} maxDistance={7} minPolarAngle={.3} maxPolarAngle={Math.PI - .3} makeDefault /></>; }

export function Furniture3DViewer(props: Furniture3DViewerProps) { const controlsRef = useRef<ControlsApi | null>(null); const [saveImage, setSaveImage] = useState<(() => void) | null>(null); const model = getFurnitureModel(props.furnitureType); const reset = () => controlsRef.current?.reset(); return <div className="furniture-3d-viewer" aria-label={`${props.furnitureType} interactive 3D preview`}><Canvas shadows fallback={<div className="viewer-unavailable">Interactive preview unavailable in this browser.</div>} dpr={[1, 1.75]} camera={{ position: [3.1, 2.15, 4.1], fov: 34 }} gl={{ antialias: true, preserveDrawingBuffer: true }}><ViewerScene props={props} controlsRef={controlsRef} onSaveImage={setSaveImage} /></Canvas><div className="viewer-status"><span>360° STUDIO VIEW</span><small>{model.kind === "gltf" ? "INTERACTIVE MODEL" : "LIVE FURNITURE PREVIEW"}</small></div><div className="viewer-controls"><button type="button" onClick={reset}>Reset view</button><button type="button" onClick={() => controlsRef.current?.dollyIn(1.25)}>+</button><button type="button" onClick={() => controlsRef.current?.dollyOut(1.25)}>−</button><button type="button" onClick={() => saveImage?.()}>Save image</button></div><div className="viewer-caption">Drag to rotate · Scroll to zoom</div></div>; }
